[package]
name = "fancy_clap"
version = "0.0.1"
edition = "2021"
author = "EndermanbugZJFC <endermanbugz@gmail.com>"
repository = "https://github.com/Endermanbugzjfc/fancy_clap"
license = "MIT"

[dependencies]
clap = "4.5.27"
clap_lex = "0.7.4"
miette = "7.4.0"
